//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealTimeArousalDetection.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700")]
        public double MinAbsoluteArousalArea {
            get {
                return ((double)(this["MinAbsoluteArousalArea"]));
            }
            set {
                this["MinAbsoluteArousalArea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700")]
        public double MinAverageArousalArea {
            get {
                return ((double)(this["MinAverageArousalArea"]));
            }
            set {
                this["MinAverageArousalArea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public double MaxAbsoluteArousalArea {
            get {
                return ((double)(this["MaxAbsoluteArousalArea"]));
            }
            set {
                this["MaxAbsoluteArousalArea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public double MaxAverageArousalArea {
            get {
                return ((double)(this["MaxAverageArousalArea"]));
            }
            set {
                this["MaxAverageArousalArea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.05")]
        public double MinAbsoluteTonicAmplitude {
            get {
                return ((double)(this["MinAbsoluteTonicAmplitude"]));
            }
            set {
                this["MinAbsoluteTonicAmplitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.05")]
        public double MinAverageTonicAmplitude {
            get {
                return ((double)(this["MinAverageTonicAmplitude"]));
            }
            set {
                this["MinAverageTonicAmplitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.12")]
        public double MaxAbsoluteTonicAmplitude {
            get {
                return ((double)(this["MaxAbsoluteTonicAmplitude"]));
            }
            set {
                this["MaxAbsoluteTonicAmplitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.12")]
        public double MaxAverageTonicAmplitude {
            get {
                return ((double)(this["MaxAverageTonicAmplitude"]));
            }
            set {
                this["MaxAverageTonicAmplitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int NumberParticipants {
            get {
                return ((int)(this["NumberParticipants"]));
            }
            set {
                this["NumberParticipants"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:/Users/ddessy/log.txt")]
        public string LogFile {
            get {
                return ((string)(this["LogFile"]));
            }
            set {
                this["LogFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double CalibrationMinArousalArea {
            get {
                return ((double)(this["CalibrationMinArousalArea"]));
            }
            set {
                this["CalibrationMinArousalArea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double CalibrationMaxArousalArea {
            get {
                return ((double)(this["CalibrationMaxArousalArea"]));
            }
            set {
                this["CalibrationMaxArousalArea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-100")]
        public double CalibrationMaxTonicAmplitude {
            get {
                return ((double)(this["CalibrationMaxTonicAmplitude"]));
            }
            set {
                this["CalibrationMaxTonicAmplitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double MinArousalArea {
            get {
                return ((double)(this["MinArousalArea"]));
            }
            set {
                this["MinArousalArea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double MaxArousalArea {
            get {
                return ((double)(this["MaxArousalArea"]));
            }
            set {
                this["MaxArousalArea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double MinTonicAmplitude {
            get {
                return ((double)(this["MinTonicAmplitude"]));
            }
            set {
                this["MinTonicAmplitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-100")]
        public double MaxTonicAmplitude {
            get {
                return ((double)(this["MaxTonicAmplitude"]));
            }
            set {
                this["MaxTonicAmplitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public double DefaultTimeWindow {
            get {
                return ((double)(this["DefaultTimeWindow"]));
            }
            set {
                this["DefaultTimeWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double CalibrationMinTonicAmplitude {
            get {
                return ((double)(this["CalibrationMinTonicAmplitude"]));
            }
            set {
                this["CalibrationMinTonicAmplitude"] = value;
            }
        }
    }
}
